# Generated by Django 6.0.5 on 2026-05-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0003_lobby'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lobby',
            new_name='LobbyGroup',
        ),
        migrations.AddField(
            model_name='user',
            name='current_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='fulabra_app.lobbygroup'),
        ),
    ]
