# Generated by Django 6.0.5 on 2026-05-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0005_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbygroup',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
