# Generated by Django 6.0.5 on 2026-05-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0007_alter_lobbygroup_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbygroup',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
