# Generated by Django 6.0.5 on 2026-05-24 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0008_alter_lobbygroup_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbygroup',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_lobby', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
