# Generated by Django 6.0.5 on 2026-05-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fulabra_app", "0005_user_avatar_user_nickname_user_stars_user_wins_and_more"),
        ("fulabra_app", "0010_alter_lobbygroup_leader"),
    ]

    operations = []
