# Generated by Django 6.0.5 on 2026-05-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulabra_app", "0011_merge_20260525_1430"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="friends",
        ),
        migrations.AddField(
            model_name="friendrequest",
            name="friends",
            field=models.ManyToManyField(blank=True, to="fulabra_app.friendrequest"),
        ),
    ]
