# Generated by Django 6.0.5 on 2026-05-25 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulabra_app", "0012_remove_user_friends_friendrequest_friends"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendrequest",
            name="friends",
        ),
        migrations.AddField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
