# Generated by Django 6.0.5 on 2026-05-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulabra_app", "0013_remove_friendrequest_friends_user_friends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatars/default_avatar.png", upload_to="avatars/"
            ),
        ),
    ]
