# Generated by Django 6.0.5 on 2026-06-02 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0014_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='current_lobby',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='lobbygroup',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('starting', 'Starting Countdown'), ('playing', 'In Game'), ('finished', 'Game Over')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='lobbygroup',
            name='code',
            field=models.CharField(db_index=True, editable=False, max_length=6, unique=True),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('avatar', models.ImageField(default='avatars/default_avatar.png', upload_to='avatars/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LobbyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='fulabra_app.lobbygroup')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='fulabra_app.player')),
            ],
        ),
        migrations.AlterField(
            model_name='lobbygroup',
            name='leader',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_lobby', to='fulabra_app.player'),
        ),
    ]
