# Generated by Django 6.0.5 on 2026-06-10 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0015_remove_user_avatar_remove_user_current_lobby_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='lobbygroup',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Players'), ('playing', 'In Game'), ('finished', 'Game Over')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='lobbyplayer',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_memberships', to='fulabra_app.lobbygroup'),
        ),
        migrations.AlterField(
            model_name='lobbyplayer',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_membership', to='fulabra_app.player'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('start', 'The game starts'), ('choosing', 'Waiting for everyone to choose a word'), ('round_result', 'Showing the round result'), ('finished', 'Game Over')], default='start', max_length=20)),
                ('lobby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fulabra_app.lobbygroup')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_memberships', to='fulabra_app.game')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_membership', to='fulabra_app.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fulabra_app.game')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_words', to='fulabra_app.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_words', to='fulabra_app.gameround')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitts', to='fulabra_app.word')),
            ],
            options={
                'unique_together': {('round', 'player')},
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
