# Generated by Django 6.0.5 on 2026-06-10 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0016_word_alter_lobbygroup_status_alter_lobbyplayer_lobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lobby',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='fulabra_app.lobbygroup'),
        ),
    ]
