# Generated by Django 6.0.5 on 2026-06-14 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0017_alter_game_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameround',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='fulabra_app.game'),
        ),
    ]
