# Generated by Django 6.0.5 on 2026-06-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fulabra_app", "0016_notification"),
        ("fulabra_app", "0018_alter_gameplayer_score_alter_gameround_game"),
    ]

    operations = []
