# Generated by Django 6.0.5 on 2026-06-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0019_merge_20260616_2354'),
        ('fulabra_app', '0022_alter_game_category'),
    ]

    operations = [
    ]
