# Generated by Django 6.0.5 on 2026-06-28 00:35

import django.db.models.deletion
import fulabra_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0022_alter_game_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.ForeignKey(default=fulabra_app.models.Game.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='fulabra_app.category'),
        ),
        migrations.AlterField(
            model_name='submittedword',
            name='word',
            field=models.ForeignKey(default=fulabra_app.models.SubmittedWord.get_default_word, on_delete=django.db.models.deletion.CASCADE, related_name='submitts', to='fulabra_app.word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='fulabra_app.category'),
        ),
    ]
