# Generated by Django 6.0.5 on 2026-06-29 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0023_alter_game_category_alter_submittedword_word_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='games_won', to='fulabra_app.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='fulabra_app.lobbygroup'),
        ),
    ]
