# Generated by Django 6.0.5 on 2026-06-29 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0024_game_winners_alter_game_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
    ]
