# Generated by Django 6.0.5 on 2026-06-29 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0025_alter_game_winners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_membership', to='fulabra_app.player'),
        ),
        migrations.AlterUniqueTogether(
            name='gameplayer',
            unique_together={('game', 'player')},
        ),
    ]
