# Generated by Django 6.0.5 on 2026-06-29 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0026_alter_gameplayer_player_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='fulabra_app.lobbygroup'),
        ),
    ]
