# Generated by Django 6.0.5 on 2026-06-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0023_merge_20260623_1605'),
        ('fulabra_app', '0027_alter_game_lobby'),
    ]

    operations = [
    ]
