# Generated by Django 6.0.5 on 2026-07-05 20:54

import fulabra_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulabra_app', '0028_merge_0023_merge_20260623_1605_0027_alter_game_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobbygroup',
            name='code',
            field=models.CharField(db_index=True, default=fulabra_app.models.LobbyGroup.generate_unique_code, editable=False, max_length=6, unique=True),
        ),
    ]
